services:
  - type: web
    name: shl-ai-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    runtime: python
    pythonVersion: 3.10.13
